web:
  image: knollit/http_frontend:latest
  ports:
   - "6080:80"
  environment:
    TLS_CERT_PATH: /dev-client.crt
    TLS_KEY_PATH: /dev-client.key
  links:
    - organizations:orgsvc
    - endpoints:endpointsvc
organizations:
  image: knollit/organization_svc:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    TLS_CA_PATH: /dev-ca.crt
    TLS_CERT_PATH: /dev-server.crt
    TLS_KEY_PATH: /dev-server.key
  links:
    - organizations_db:postgres
organizations_db:
  image: knollit/organization_svc_rdbms:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
endpoints:
  image: knollit/endpoint_svc:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    TLS_CA_PATH: /dev-ca.crt
    TLS_CERT_PATH: /dev-server.crt
    TLS_KEY_PATH: /dev-server.key
  links:
    - endpoints_db:postgres
endpoints_db:
  image: knollit/endpoint_svc_rdbms:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
