web:
  image: knollit/http_frontend:latest
  ports:
   - "6080:80"
  environment:
    TLS_CERT_PATH: /dev-client.crt
    TLS_KEY_PATH: /dev-client.key
  links:
    - organization_svc:orgsvc
    - endpoint_svc:endpointsvc
organization_svc:
  image: knollit/organization_svc:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    TLS_CA_PATH: /dev-ca.crt
    TLS_CERT_PATH: /dev-server.crt
    TLS_KEY_PATH: /dev-server.key
  links:
    - organization_svc_rdbms:postgres
organization_svc_rdbms:
  image: knollit/organization_svc_rdbms:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
endpoint_svc:
  image: knollit/endpoint_svc:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    TLS_CA_PATH: /dev-ca.crt
    TLS_CERT_PATH: /dev-server.crt
    TLS_KEY_PATH: /dev-server.key
  links:
    - endpoint_svc_rdbms:postgres
endpoint_svc_rdbms:
  image: knollit/endpoint_svc_rdbms:latest
  environment:
    POSTGRES_PASSWORD: mysecretpassword
